# 7
waypoints: # [x,y,z,yaw_angle]
  [
    [1.1, 1.2, -3.6, -35],
    [8.2, 6.0, -3.0, 0],
    [-7.2, 5.0, -3.2, 0],
    [7.5, -6.5, -3.5, 0],
    [-7.5, -8, -2, 0],
    [1, -6.2, -3, 0],
    [-6, -2, -2.2, 0],
  ]

distance_tol: 0.3

loop: False
# if path is a loop, first waypoint will be constarined to be the last waypoint
# if path is not a loop, first waypoint will be constarined to be the takeoff pos, which will not be optimized
# and the last waypoint will be constrined to be the landing pos, which will not be optimized
